### ISSUE TITLE
bower.io/search not working on Firefox

### ISSUE THREAD

**Issue by younessm** [bower/bower.github.io#150] opened 2015-07-31 19:51 UTC
<h2>Package Search page not working on Firefox for Ubuntu</h2>
i'm using Ubuntu 14.04, Firefox 39.0
Same issue on Firefox Developer Edition 41.0a2 
![screenshot from 2015-07-31 20 46 47](https://cloud.githubusercontent.com/assets/10441428/9016070/79b6664c-37bd-11e5-8455-f9a0a3012fd9.png)

<h4>Error Log</h4>
"Error: group[0].website is undefined
[7]</module.exports/</dedupe/<@http://bower.io/search/dist/app.js:9:10193
runInContext/forOwn@http://bower.io/search/dist/app.js:8:28187
forEach@http://bower.io/search/dist/app.js:8:2954
[7]</module.exports/</dedupe@http://bower.io/search/dist/app.js:9:10113
[7]</module.exports/</$scope.search@http://bower.io/search/dist/app.js:9:10980
[7]</module.exports/<@http://bower.io/search/dist/app.js:9:11887
invoke@http://bower.io/search/dist/app.js:2:3636
instantiate@http://bower.io/search/dist/app.js:2:3861
$ControllerProvider/this.$get</<@http://bower.io/search/dist/app.js:3:8735
nodeLinkFn/<@http://bower.io/search/dist/app.js:2:24067
forEach@http://bower.io/search/dist/app.js:1:9054
nodeLinkFn@http://bower.io/search/dist/app.js:2:23738
compositeLinkFn@http://bower.io/search/dist/app.js:2:15683
compile/<@http://bower.io/search/dist/app.js:2:14601
bootstrap/doBootstrap/</<@http://bower.io/search/dist/app.js:1:18365
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://bower.io/search/dist/app.js:4:19223
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://bower.io/search/dist/app.js:4:19576
bootstrap/doBootstrap/<@http://bower.io/search/dist/app.js:1:18306
invoke@http://bower.io/search/dist/app.js:2:3636
bootstrap/doBootstrap@http://bower.io/search/dist/app.js:1:18178
bootstrap@http://bower.io/search/dist/app.js:1:18499
angularInit@http://bower.io/search/dist/app.js:1:17669
[2]</</<@http://bower.io/search/dist/app.js:7:13247
trigger@http://bower.io/search/dist/app.js:5:20371
createEventHandler/eventHandler/<@http://bower.io/search/dist/app.js:1:31559
forEach@http://bower.io/search/dist/app.js:1:8900
createEventHandler/eventHandler@http://bower.io/search/dist/app.js:1:31520

**Comment by fmoliveira** [comment] 2015-08-05 11:51
Duplicate of https://github.com/bower/search/issues/72 .

**Closed** 2015-08-06 09:36 UTC
